// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD38cTPDCiifQ_b8-rksY8HB0vUNfwlcIo',
    appId: '1:672108873725:web:43dbcb57cc81174ca8bb94',
    messagingSenderId: '672108873725',
    projectId: 'chess2-f60e8',
    authDomain: 'chess2-f60e8.firebaseapp.com',
    storageBucket: 'chess2-f60e8.firebasestorage.app',
    measurementId: 'G-6SQFSJP2R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqyNLIF0YdFzVVJ8TBkXzpN2ktcyq4B5g',
    appId: '1:672108873725:android:ba6b313bda16d54ea8bb94',
    messagingSenderId: '672108873725',
    projectId: 'chess2-f60e8',
    storageBucket: 'chess2-f60e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrh9RjoERXD8OIyYBDikZSCkk_CN7SCU',
    appId: '1:672108873725:ios:2ed122e109dbbcafa8bb94',
    messagingSenderId: '672108873725',
    projectId: 'chess2-f60e8',
    storageBucket: 'chess2-f60e8.firebasestorage.app',
    iosBundleId: 'com.example.simpleChessBoardUsage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMrh9RjoERXD8OIyYBDikZSCkk_CN7SCU',
    appId: '1:672108873725:ios:2ed122e109dbbcafa8bb94',
    messagingSenderId: '672108873725',
    projectId: 'chess2-f60e8',
    storageBucket: 'chess2-f60e8.firebasestorage.app',
    iosBundleId: 'com.example.simpleChessBoardUsage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD38cTPDCiifQ_b8-rksY8HB0vUNfwlcIo',
    appId: '1:672108873725:web:1e581e88bb9e3009a8bb94',
    messagingSenderId: '672108873725',
    projectId: 'chess2-f60e8',
    authDomain: 'chess2-f60e8.firebaseapp.com',
    storageBucket: 'chess2-f60e8.firebasestorage.app',
    measurementId: 'G-H3DYX70ENF',
  );
}
